    LIST P=16F887
    #INCLUDE "p16F887.inc"
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
   COUNT1			EQU		    0X20
   COUNT2			EQU		    0X21
   CLAVE			EQU		    0X22
   RESULTADO		EQU		    0X30
    ORG		 0X00
    GOTO		 START 
    ;0X04
    ORG		 0X05
START: 
    BANKSEL		ANSEL
    CLRF		ANSEL
    CLRF		ANSELH
    BANKSEL		TRISA
    MOVLW		B'11110000'	;RB7-RB4 ENTRADAS DE TECLADO
    MOVWF		TRISB		;RB3-RB0 SALIDAS 
    CLRF		TRISA
    BANKSEL		OPTION_REG
    BCF		OPTION_REG, 7 ; Habilita las resistencias pull-up en PORTB
    BANKSEL		PORTA
    CLRF		CLAVE
MAIN:
    CALL		TESTEO_COLUMNAS
    CALL		TABLA
    MOVWF		RESULTADO
    GOTO		MAIN
    
TESTEO_COLUMNAS:
    MOVF		CLAVE,W
    CALL		TABLA
    MOVWF		PORTB
    MOVLW		B'00000001'
    MOVWF		PORTB
    CALL		FILA1
    MOVLW		B'00000010'
    MOVWF		PORTB
      CALL		FILA2
    MOVLW		B'00000100'
    MOVWF		PORTB
      CALL		FILA3
    MOVLW		B'00001000'
    MOVWF		PORTB
    CALL		FILA4
    RETURN
    ;-----------------TECLADOO-------------
FILA1:
    BTFSS		PORTB,4
    GOTO		NUM2
    MOVLW		.0
    MOVWF		CLAVE
    RETURN
    NUM2:
	    BTFSS	PORTB,5
	    GOTO	NUM3
	    MOVLW	.1
	    MOVWF	CLAVE
	    RETURN		
    NUM3:
	    BTFSS	PORTB,6
	    GOTO	NUM4
	    MOVLW	.2
	    MOVWF	CLAVE
	    RETURN
    NUM4:
	    BTFSS	PORTB,7
	    GOTO	FILA2
	    MOVLW	.3
	    MOVWF	CLAVE
	    RETURN
FILA2:
    BTFSS		PORTB,4
    GOTO		NUM6
    MOVLW		.4
    MOVWF		CLAVE
    RETURN
NUM6:
	BTFSS	PORTB,5
	GOTO	NUM7
	MOVLW	.5
	MOVWF	CLAVE
	RETURN
NUM7:
	BTFSS	PORTB,6
	GOTO	NUM8
	MOVLW	.6
	MOVWF	CLAVE
	RETURN
NUM8:
	BTFSS	PORTB,7
	GOTO	FILA3
	MOVLW	.7
	MOVWF	CLAVE
	RETURN
FILA3:
    BTFSS		PORTB,4
    GOTO		NUMA
    MOVLW		.8
    MOVWF		CLAVE
    RETURN
NUMA:
	BTFSS	PORTB,5
	GOTO	NUMB
	MOVLW	.9
	MOVWF	CLAVE
	RETURN
NUMB:
	BTFSS	PORTB,6
	GOTO	NUMC
	MOVLW	.10
	MOVWF	CLAVE
	RETURN
NUMC:
	BTFSS	PORTB,7
	GOTO	FILA4
	MOVLW	.11
	MOVWF	CLAVE
	RETURN
FILA4:
    BTFSS		PORTB,4
    GOTO		NUME
    MOVLW		.12
    MOVWF		CLAVE
    RETURN
NUME:
	BTFSS	PORTB,5
	GOTO	NUMF
	MOVLW	.13
	MOVWF	CLAVE
	RETURN
NUMF:
	BTFSS	PORTB,6
	GOTO	NUM0
	MOVLW	.14
	MOVWF	CLAVE
	RETURN
NUM0:
	BTFSS	PORTB,7
	RETURN
	MOVLW	.15
	MOVWF	CLAVE
	RETURN

DELAY_20MS: ;Delay para mantener encendido el led
    MOVLW		.100
    MOVWF		COUNT1
L1:
    MOVLW		 .50
    MOVWF		COUNT2
L2:
    DECFSZ		COUNT2
    GOTO		L2
    DECFSZ		COUNT1
    GOTO		L1
    RETURN
TABLA:
    MOVF		CLAVE,W
    ADDWF		PCL,F
    ;en ASCII
    RETLW		.49;1
    RETLW		.50;2
    RETLW		.51;3
    RETLW		.52;4
    
    RETLW		 .53;5
    RETLW		 .54;6
    RETLW		 .55 ;7
    RETLW		 .56 ;8
    
    RETLW		 .57;9
    RETLW		 .65;A
    RETLW		.66;B
    RETLW		.67;C
    
    RETLW		.68;D
    RETLW		.69;E
    RETLW		.70;F
     RETLW		48;0
     
    RETLW		B'0111101'
    RETLW		B'1111110'
    RETLW		B'1001111'
    RETLW		B'1000111'
    END