; ** Encabezado **
    LIST P=16F887			

    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20
CONTADOR2	EQU		 0x21
NUM_C		EQU		 0x22
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24
    ORG		0x00
    GOTO		START
    ORG		0X04
    GOTO		INTERRUPCION
    ORG		0X05
    GOTO START
    
START:
    ;CONFIGURO PUERTOS
    BANKSEL		ANSEL
    CLRF		ANSEL		;0 PARA PINES DIGITAL
    CLRF		ANSELH
    BANKSEL		TRISA
 	;ENTRADA LLAVE PIN 7 DE PORTB
    BSF		TRISB,0
    CLRF		TRISD
    BANKSEL		PORTA
    CLRF		PORTD
    
    ;----------------------------
    MOVLW		 0X70		  ;DESDE 70h ESTAN REFLEJADAS EN LOS 4 BANCOS
    MOVWF		 FSR 
    
    MOVLW		.10		   
    MOVWF		NUM_C		   
;---------------------CONFIGURO INT-------------------------
    BANKSEL		WPUB
    BSF		WPUB,0
     BANKSEL	OPTION_REG     
     BCF		OPTION_REG,7;HABILITO LAS PULL UP
     BCF		OPTION_REG, INTEDG ;SELEECION EL FLANCO. INTERRUPCION POR FLANCO DESCENDENTE CON O
				  ;CUANDO PULSO PULSADOR  SE VA A TIERRA
    BANKSEL		PORTA
    BCF		INTCON,INTF	    ;BORRA FLAG INTERRUPCION DEL RBO  DE FLANCO
    BSF		INTCON,7		    ;SETEA     GIE  GLOBAL5
     BSF		INTCON,INTE	;SETEA INTE PARA INTERRUOCION DEL RBO POR FLANCO DESCENDENTE}
    BANKSEL	PORTA
    ;----------------------------CARGO NUMEROS AL DESDE 70h A 79h CON EL IINDF----------------------------
   MOVLW		B'10000001'		;0
   MOVWF		INDF
   INCF		 FSR,1
    MOVLW		B'11001111'		 ; 1
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 B'10010010'		 ; 2
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 B'10000110'		; 3
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 B'11001100'		; 4
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 B'10100100'		; 5
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 B'10100000'		 ; 6
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		B'10001111'		 ; 7
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 B'10000000'	 ; 8
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		B'10001100'		 ; 9
    MOVWF		 INDF
    
    MOVLW		 0X70		 ; RESETEO EL FSR
    MOVWF		 FSR
    
    ;................ PONGO EL PORTB CON UN  NUMERO INICIAL
    MOVF		INDF,W
    MOVWF		PORTD		;PORTB TIENE EL NUMERO CERO
  
    ;.............................PROGRAMA PRINCIPAL ., VERIFICA SI HAY INTERRUPCION ---------------------------------------
    GOTO		$
INTERRUPCION:	
   BCF		INTCON,INTF	;LIMPIO FLAG. ESTE ES DE INTERRUPCION DEL RB0 POR FLANCO DESCENDENTE
    ; ----------------------GUARDO CONTEXTO-------------------------
    MOVWF		DOBLEV
    SWAPF		STATUS,W
    MOVWF		ESTADO
    ;------------------------;ANTIREBOTE
   
    ;----LOGICA INTERRUPCION-----------

    CALL		ANTIREBOTE
    
    ;----------------CARGO CONTEXTO-----------
CONTEXTO:
    SWAPF		ESTADO,W
    MOVWF		STATUS
    SWAPF		DOBLEV,1
    SWAPF		DOBLEV,0
    
    ;---------------.VUELVO------------------
    RETFIE
    
ANTIREBOTE:
    CALL		DELAY
    BTFSC		PORTB,0      	    ;
    RETURN	;SALE
    CALL		CARGAR
    RETURN
CARGAR:
    MOVF		INDF,W		    ;INDF CONTIENE EL NUMERO 0. PORQUE FSR APUNTA AL 70h
    MOVWF		PORTD		    ;CARGA DE NUMEROS
    INCF		 FSR,1
    
    DECFSZ		 NUM_C		    ;DISMUNUYO LA CUENTA DE NUEMEROS A CARGAR
    RETURN
    ;----------------------------SI LOS NUMEROS YA LLEGARON A 9:  ---------------------------
    MOVLW		0x70		    ;SETEO LA DIRECCION DE NUEVO EN 70h
    MOVWF		FSR
    MOVLW		 .10		    ;SETEO DE NUEVO EL CONTADOR 
    MOVWF		NUM_C
    RETURN		
DELAY:
    MOVLW		.50
    MOVWF		CONTADOR1
L1:
    MOVLW		 .50
    MOVWF		 CONTADOR2
L2:	
    DECFSZ		 CONTADOR2, F
    GOTO		  L2
    DECFSZ		 CONTADOR1, F
    GOTO		   L1
    RETURN
	
    
    
    
    END
 