; ** Encabezado **
    LIST P=16F887			
    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20
CONTADOR2	EQU		 0x21
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24

    ORG		0x00
    GOTO		START
    ORG		0X04
    GOTO		INTERRUPCION
    ORG		0x05
    GOTO START
    
    
START:
	BANKSEL			ANSEL
	CLRF			ANSEL
	CLRF			ANSELH
	BANKSEL			TRISA
	BSF			TRISA,4
	BSF			TRISB,0
	CLRF			TRISD
	BANKSEL			PORTA
	CLRF			PORTA 
	CLRF			PORTB
	
	
	;ESTOY EN EL BANCO DONDE ETA OPTION_REG Y INTCON APROVECHO DE CONFIGURAR AMBOS REGISTROS 
	BANKSEL			INTCON
	BSF			INTCON,GIE		;HABILITO INTERRUPCION GLOBAL
	BSF			INTCON,INTE		
	BCF			INTCON,INTF		;LIMPIO EL FLAG DE INTERRUPCION
	BANKSEL			OPTION_REG
	BCF			OPTION_REG,INTEDG
	
	
	BANKSEL			PORTA
	CLRF			PORTD
	MAIN:
	    CALL			DELAY
	    BTFSS			PORTA,4
	    GOTO			PARPADEO ;SI ES 0 CERO
	    GOTO			MAIN
	PARPADEO:
	    MOVLW			0XFF
	    MOVWF			PORTD
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CLRF			PORTD
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    GOTO			PARPADEO
INTERRUPCION:
    ;----------------BORRO EL FLAG DE INT 
	BCF			INTCON,INTF ;POR RB0
    ;-----------------------CARGO CONTEXTO
	MOVWF			DOBLEV
	SWAPF			STATUS,W
	MOVWF			ESTADO
	
    ;----------------LOGICA ------------------------
	CALL			DELAY	;DELAY PARA ANTIREBOTE
	BTFSS			PORTB,0
	GOTO			PARAR
	GOTO			DEVUELVOCONTEXTO
	PARAR:
	    CLRF			PORTD
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
    
   ;-------------------------------DEVUELVO CONTEXTO
DEVUELVOCONTEXTO:
	SWAPF			ESTADO,W
	MOVWF			STATUS
	SWAPF			DOBLEV,1
	SWAPF			DOBLEV,W
   
	RETFIE			    ;HABILITO EL GLOBAL GIE
    
	
DELAY:
    MOVLW   50        ; Primer contador
    MOVWF   CONTADOR1
L1_20MS:
    MOVLW   50         ; Segundo contador
    MOVWF   CONTADOR2
L2_20MS:
    DECFSZ  CONTADOR2, F
    GOTO    L2_20MS
    DECFSZ  CONTADOR1, F
    GOTO    L1_20MS
    RETURN
	
DELAY_1S:
    MOVLW   250         ; Primer contador
    MOVWF   CONTADOR1
L1_1S:
    MOVLW   250         ; Segundo contador
    MOVWF   CONTADOR2
L2_1S:
    DECFSZ  CONTADOR2, F
    GOTO    L2_1S
    DECFSZ  CONTADOR1, F
    GOTO    L1_1S
    RETURN
    
    
    END