; ** Encabezado **
    LIST P=16F887			
    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20
CONTADOR2	EQU		 0x21
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24


    ORG		0x00
    GOTO		START
    ORG		0X04
    GOTO		INTERRUPCION
    ORG		0x05
    GOTO START
    
    
START:
	BANKSEL			ANSEL
	CLRF			ANSEL
	CLRF			ANSELH
	BANKSEL			TRISA
	MOVLW			b'00000110'		;ENTRADA RB1,RB2.
	MOVWF			TRISB			;SALIDA: RB3
	BANKSEL			PORTA
	BCF			PORTB,1
	BCF			PORTB,2
	BCF			PORTB,3
	
	
	;ESTOY EN EL BANCO DONDE ETA OPTION_REG Y INTCON APROVECHO DE CONFIGURAR AMBOS REGISTROS 
	BANKSEL			OPTION_REG	
	BSF			INTCON,GIE	;HABILITO INTERRUPCION GLOBAL
	BSF			INTCON,RBIE	
	BCF			INTCON,RBIF	;LIMPIO EL FLAG DE INTERRUPCION
	BSF			IOCB,1
	BSF			IOCB,2
	BANKSEL			PORTA
	CLRF			PORTB
	BCF			PORTB,3
    GOTO $-1
    
    
INTERRUPCION:

    ;-----------------------CARGO CONTEXTO
	MOVWF			DOBLEV
	SWAPF			STATUS,W
	MOVWF			ESTADO
	
    ;----------------LOGICA ------------------------
	    CALL			DELAY_3S
	    BTFSS			PORTB,1
	    GOTO			CEROS		;00   O  01
	    GOTO			UNOS		;11   O   10
	CEROS:
	   
	    BTFSS			PORTB,2
	    GOTO			OO
	    GOTO			IO
	UNOS:
	    
	    BTFSS			PORTB,2
	    GOTO			OI
	    GOTO			II
	    OO:
		 CALL		    DELAY_20MS
		 ;ANTIREBOTE SI NO SE PRESIONO NADA
		 BTFSC		    PORTB,1
		 GOTO DEVUELVOCONTEXTO
		 BTFSC		    PORTB,2
		GOTO		   DEVUELVOCONTEXTO
		BSF		    PORTB,3
		CALL		    UN_MIN_RELE
		CALL		    UN_MIN_RELE
		CALL		    UN_MIN_RELE
		BCF		    PORTB,3
		GOTO		    DEVUELVOCONTEXTO
	    OI:
		 CALL		    DELAY_20MS
		 ;ANTIREBOTE SI NO SE PRESIONO NADA
		BTFSS		    PORTB,1
		GOTO		    DEVUELVOCONTEXTO
		BSF		    PORTB,3
		CALL		    UN_MIN_RELE
		BCF		    PORTB,3
		GOTO		     DEVUELVOCONTEXTO
	    IO:
		CALL		   DELAY_20MS
		BTFSS		    PORTB,2
		GOTO		    DEVUELVOCONTEXTO
		BSF		    PORTB,3
		CALL		    UN_MIN_RELE
		CALL		    UN_MIN_RELE
		BCF		    PORTB,3
		GOTO		    DEVUELVOCONTEXTO
	    II:
		CALL		   DELAY_20MS
		 ;ANTIREBOTE SI NO SE PRESIONO NADA
		 BTFSC		    PORTB,1
		 NOP
		 BTFSS		    PORTB,2
		GOTO		   DEVUELVOCONTEXTO
		BCF		    PORTB,3
		GOTO		   DEVUELVOCONTEXTO	;NO HACE NADA
    

   ;-------------------------------DEVUELVO CONTEXTO
   
   
DEVUELVOCONTEXTO:
	BCF			PORTB,3
	BCF			INTCON,RBIF
	SWAPF			ESTADO,W
	MOVWF			STATUS
	SWAPF			DOBLEV,1
	SWAPF			DOBLEV,W
   
	
	    ;----------------BORRO EL FLAG DE INT 
	BCF			INTCON,RBIF
   RETFIE			    ;HABILITO EL GLOBAL GIE
    
DELAY_20MS:
    MOVLW       .200  ; CONTADOR1
    MOVWF       CONTADOR1
L1_20:
    MOVLW       .100  ; CONTADOR2
    MOVWF       CONTADOR2
L2_20:
    DECFSZ      CONTADOR2, F
    GOTO        L2_20
    DECFSZ      CONTADOR1, F
    GOTO        L1_20
    RETURN
	
UN_MIN_RELE:
    MOVLW       .250  ; CONTADOR1 (ajuste para mayor duración)
    MOVWF       CONTADOR1
L1_1MIN:
    MOVLW       .250  ; CONTADOR2
    MOVWF       CONTADOR2
L2_1MIN:
    DECFSZ      CONTADOR2, F
    GOTO        L2_1MIN
    DECFSZ      CONTADOR1, F
    GOTO        L1_1MIN
    RETURN
    
DELAY_3S:
    MOVLW       .250  ; CONTADOR1
    MOVWF       CONTADOR1
L1_3S:
    MOVLW       .250  ; CONTADOR2
    MOVWF       CONTADOR2
L2_3S:
    DECFSZ      CONTADOR2, F
    GOTO        L2_3S
    DECFSZ      CONTADOR1, F
    GOTO        L1_3S
    RETURN
    END