; ** Encabezado **
    LIST P=16F887
    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20		    ;delay
CONTADOR2	EQU		 0x21		    ;delay
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24
LEDS		EQU		 0X25
CONT_TIMER	EQU		 0X26
CONT_ESTADOS	EQU		0X27
CONTADOR3	EQU		0X28
    ORG		0x00
    GOTO		START
    ORG		0X04
    GOTO		INTERRUPCION
    ORG		0x05
    GOTO START
    
START:
    BANKSEL		ANSEL
    CLRF		ANSEL
    CLRF		ANSELH
    
    
    BANKSEL		TRISA
    BSF		TRISB,0		 ;PUERDO B_0  COMO ENTRADA . LLAVE
    ;----------------------------LEDS DE PEATON
    BCF		TRISA,0		 ;ROJO
    BCF		TRISA,1		 ;AMARILLO
    BCF		TRISA,2		;VERDE
    ;----------------------------LEDS DE VEHICULO
    BCF		TRISA,3		;ROJO
    BCF		TRISA,4		;AMARILLO
    BCF		TRISA,5		 ;VERDE
    
    BANKSEL		PORTA
    CLRF		PORTA
    
    BANKSEL		INTCON	;BANCO 1
    ;-------CONFIG INTERRUPCION------------PARA LA LLAVE------------
    BCF		INTCON,INTF	;LIMPIO EL FLAG DE RBO 
    BSF		INTCON,GIE	;HABILITO EL GIE
    BSF		INTCON,INTE	;LLAVE DEL INTE PARA RBO
    
    ;-------------CONFIG PARA TIMER-------------
    BCF		INTCON,T0IF	    ;BORRO FLAG DE TIMER
    BSF		INTCON,T0IE	    ;HABILITO INTERRUPCION TIMER
   BANKSEL		OPTION_REG
   
   ;BSF		OPTION_REG,NOT_RBPU; POR FLANCO SUBIDA
   
    BCF		OPTION_REG,T0CS	 ;SELECCIONO TIMER POR CONTADOR DE INSTRUCCIONES
    ;-----CONGIGURO PRESCALER----
    BSF		OPTION_REG,PS0
    BSF		OPTION_REG,PS1
    BSF		OPTION_REG,PS2
    BCF		OPTION_REG, PSA   ; asignar prescaler al TIMER0

    BSF		OPTION_REG, INTEDG 
    BCF		OPTION_REG,T0SE	    ;CONFIGURO D TRANSICIONES DE BAJO A ALTO
    
    
    BANKSEL		PORTA
    BCF		PORTA,0		 ;ROJO
    BCF		PORTA,1		 ;AMARILLO
    BCF		PORTA,2		;VERDE
    ;----------------------------LEDS DE VEHICULO
    BCF		PORTA,3		;ROJO
    BCF		PORTA,4		;AMARILLO
    BCF		PORTA,5
    CLRF		LEDS
    MOVLW		.20
    MOVWF		CONT_TIMER
    MOVLW		.9
    MOVWF		CONT_ESTADOS
    
     ;----------------------------CARGO ESTADOS DE SEMAFORO---------------------------
    MOVLW		0X30
    MOVWF		FSR
   MOVLW		b'00001100'
   MOVWF		INDF
   INCF		 FSR,1
    MOVLW		b'00001100'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		b'00001100'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		b'00001010'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 b'00100001'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 b'00100001'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		 b'00100001'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		b'00100001'
    MOVWF		 INDF
    INCF		 FSR,1
    MOVLW		b'00010001'
    MOVWF		 INDF
    MOVLW		 0X30		 ; RESETEO EL FSR
    MOVWF		 FSR
    
    ;................ PONGO EL PORTB CON UN  NUMERO INICIAL
    MOVF		INDF,W
    MOVWF		LEDS		

LOOP:
    CALL		DELAY_1S
    MOVF		LEDS,W
 ;   CALL DELAY
    MOVWF		PORTA
    GOTO LOOP
INTERRUPCION:
      ; ----------------------GUARDO CONTEXTO-------------------------
    MOVWF		DOBLEV
    SWAPF		STATUS,W
    MOVWF		ESTADO
    ;------------------------;ANTIREBOTE
    ;----LOGICA INTERRUPCION-----------
    BTFSC		INTCON,T0IF
    GOTO		SEMAFORO	    ;INTERRUPCION POR TIMER
    BTFSC		INTCON,INTF	    ;PREGUNTO SI SE LEVANTO FLAG DE RB0
    GOTO		ANTIREBOTE
    
    ;----------------CARGO CONTEXTO-----------
CONTEXTO:
   BCF		INTCON,INTF	;LIMPIO FLAG. ESTE ES DE INTERRUPCION DEL RB0 POR FLANCO DESCENDENTE
   BCF		INTCON,T0IF	    ;BORRO FLAG DE TIMER
   
   
    SWAPF		ESTADO,W
    MOVWF		STATUS
    SWAPF		DOBLEV,1
    SWAPF		DOBLEV,0
    ;---------------.VUELVO------------------
    RETFIE
ANTIREBOTE:
    BCF		INTCON,INTF  
    BCF		INTCON,T0IF 
    CALL		DELAY_20MS
    CALL		DELAY_20MS
    BTFSS		PORTB,0      	    
    GOTO		CONTEXTO	
    GOTO		RESETEAR   
RESETEAR:    
    MOVLW		.20       
    MOVWF		CONT_TIMER
    MOVLW		.9
    MOVWF		CONT_ESTADOS
    MOVLW		0X30
    MOVWF		FSR
    MOVF		INDF,W
    MOVWF		LEDS
    MOVWF		PORTA
    BCF		INTCON,INTF  
    BCF		INTCON,T0IF 
    GOTO		CONTEXTO		
SEMAFORO:
    DECFSZ		CONT_TIMER,F
    GOTO		CONTEXTO
    GOTO		CARGAR
CARGAR:
    INCF		    FSR,1
    MOVF		    INDF,W
    MOVWF		    LEDS    
    MOVLW		    .20
    MOVWF		  CONT_TIMER
    DECFSZ		    CONT_ESTADOS
    GOTO		    CONTEXTO
    GOTO		    RESETEAR
DELAY_20MS:
    MOVLW   .250      ; Carga 250 en CONTADOR1
    MOVWF   CONTADOR1 
L1:
    MOVLW   .250      ; Carga 250 en CONTADOR2
    MOVWF   CONTADOR2
L2:
    DECFSZ  CONTADOR2, F
    GOTO    L2
    DECFSZ  CONTADOR1, F
    GOTO    L1
    RETURN
DELAY_1S:
    MOVLW   .250      ; Carga 250 en CONTADOR1
    MOVWF   CONTADOR1 
LL1:
    MOVLW   .250      ; Carga 250 en CONTADOR2
    MOVWF   CONTADOR2
LL2:
    DECFSZ  CONTADOR2, F
    GOTO    LL2
    DECFSZ  CONTADOR1, F
    GOTO    LL1
    MOVLW   .40       ; Carga 40 en CONTADOR3
    MOVWF   CONTADOR3
L3:
    DECFSZ  CONTADOR3, F
    GOTO    L3
    RETURN
    END
 
