; ** Encabezado **
    LIST P=16F887			
    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20
CONTADOR2	EQU		 0x21
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24
CONTADORT EQU	0X25
    ORG		0x00
    GOTO		START
    ;ORG		0X04
    ;GOTO		INTERRUPCION
    ORG		0x05
    GOTO START
    
    
START:
	BANKSEL			ANSEL
	CLRF			ANSEL
	CLRF			ANSELH
	BANKSEL			TRISA
	BSF			TRISA,4
	BSF			TRISB,0
	CLRF			TRISD
	BANKSEL			PORTA
	CLRF			PORTA 
	CLRF			PORTB
	MOVLW	.20
	MOVWF CONTADORT
	
	
	
	BANKSEL			PORTA
	CLRF			PORTD
	MAIN:
	    MOVLW   0XFF ;PREDO LEDS
	    MOVWF   PORTD
	PREGUNTO: 
	    BTFSS   PORTB,0     ;SE PRESIONO?
	    GOTO NOPRESIONADO
	    GOTO PRESIONADO
	NOPRESIONADO:
	    CALL DELAY_50MS
	    DECFSZ CONTADORT,1 ;INICIALIZADO EN 20
	    GOTO PREGUNTO
	    ;SI NO CAMBIO DE ESTADO Y RESETEO CONTADORES
	    BTFSS PORTD,0 ;LEDS APAGADOS O PRENDIDOS? 
	    GOTO PRENDER
	    GOTO APAGAR
	    RETURN 
	PRENDER:
	    MOVLW .20 ;REINICIO CONTADOR
	    MOVWF CONTADORT
	    MOVLW 0XFF
	    MOVWF PORTD ;APAGO LEDS
	    GOTO PREGUNTO
	    RETURN
	APAGAR:
	    MOVLW .20 ;REINICIO CONTADOR
	    MOVWF CONTADORT
	    MOVLW 0X00
	    MOVWF PORTD ;APAGO LEDS
	    GOTO PREGUNTO
	    RETURN
	SEPRECIONO:
    
	    MOVLW 0X00
	    MOVWF PORTD
	    
	    
	PRESIONADO:
    
	    GOTO			PARPADEO ;SI ES 0 CERO
	    GOTO			MAIN
	PARPADEO:
	    MOVLW			0XFF
	    MOVWF			PORTD
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CLRF			PORTD
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    GOTO			PARPADEO

    

	
DELAY:
    MOVLW   50        ; Primer contador
    MOVWF   CONTADOR1
L1_20MS:
    MOVLW   50         ; Segundo contador
    MOVWF   CONTADOR2
L2_20MS:
    DECFSZ  CONTADOR2, F
    GOTO    L2_20MS
    DECFSZ  CONTADOR1, F
    GOTO    L1_20MS
    RETURN
	
DELAY_1S:
    MOVLW   250         ; Primer contador
    MOVWF   CONTADOR1
L1_1S:
    MOVLW   250         ; Segundo contador
    MOVWF   CONTADOR2
L2_1S:
    DECFSZ  CONTADOR2, F
    GOTO    L2_1S
    DECFSZ  CONTADOR1, F
    GOTO    L1_1S
    RETURN
    
    
    END