; ** Encabezado **
    LIST P=16F887			
    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20
CONTADOR2	EQU		 0x21
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24

    ORG		0x00
    GOTO		START
    ORG		0X04
    GOTO		INTERRUPCION
    ORG		0x05
    GOTO START
    
    
START:
	BANKSEL			ANSEL
	CLRF			ANSEL
	CLRF			ANSELH
	BANKSEL			TRISA
	MOVLW			b'11110000';ENTRADA RB4 RB5 RB6 RB7
	MOVWF			TRISB
	BCF			TRISA,0 ;RA0 SALIDA LED PARA COMPROBAR DELAY
	BANKSEL			PORTA
	CLRF			PORTA 
	CLRF			PORTB
	
	
	;ESTOY EN EL BANCO DONDE ETA OPTION_REG Y INTCON APROVECHO DE CONFIGURAR AMBOS REGISTROS 
	BANKSEL			INTCON
	BSF			INTCON,GIE		;HABILITO INTERRUPCION GLOBAL
	BSF			INTCON,RBIE		
	BCF			INTCON,RBIF		;LIMPIO EL FLAG DE INTERRUPCION
	
	BANKSEL			IOCB
	MOVLW			b'11110000'
	MOVWF			IOCB
	
	BANKSEL			PORTA
	
	MAIN:
	    GOTO			MAIN
    
INTERRUPCION:
    ;----------------BORRO EL FLAG DE INT 
	BCF			INTCON,RBIF
    ;-----------------------CARGO CONTEXTO
	MOVWF			DOBLEV
	SWAPF			STATUS,W
	MOVWF			ESTADO
	
    ;----------------LOGICA ------------------------
	CALL			DELAY	;DELAY PARA ANTIREBOTE
CAMBIOS:
	    BTFSS			PORTB,4 ; PREGUNTO SI RB4 FUE PRESIONADO
	    GOTO			FUEB5 ;SI NO FUE RB4 PREGUNTO EL SIGUIENTE BITS
	    BSF			PORTA,0
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    BCF			PORTA,0
	    GOTO			DEVUELVOCONTEXTO
	FUEB5:
	    BTFSS			PORTB,5
	    GOTO			FUERB6
	    BSF			PORTA,0
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    BCF			PORTA,0
	    GOTO			DEVUELVOCONTEXTO
	FUERB6:
	    BTFSS			PORTB,6
	    GOTO			FUERB7
	    BSF			PORTA,0
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    BCF			PORTA,0
	    GOTO			DEVUELVOCONTEXTO
	FUERB7:
	    BTFSS			PORTB,7
	    GOTO			DEVUELVOCONTEXTO
	    BSF			PORTA,0
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    CALL			DELAY_1S
	    BCF			PORTA,0
	    GOTO			DEVUELVOCONTEXTO
   
   ;-------------------------------DEVUELVO CONTEXTO
DEVUELVOCONTEXTO:
	SWAPF			ESTADO,W
	MOVWF			STATUS
	SWAPF			DOBLEV,1
	SWAPF			DOBLEV,W
   
	RETFIE			    ;HABILITO EL GLOBAL GIE
    
	
DELAY:
    MOVLW   50        ; Primer contador
    MOVWF   CONTADOR1
L1_20MS:
    MOVLW   50         ; Segundo contador
    MOVWF   CONTADOR2
L2_20MS:
    DECFSZ  CONTADOR2, F
    GOTO    L2_20MS
    DECFSZ  CONTADOR1, F
    GOTO    L1_20MS
    RETURN
	
DELAY_1S:
    MOVLW   250         ; Primer contador
    MOVWF   CONTADOR1
L1_1S:
    MOVLW   250         ; Segundo contador
    MOVWF   CONTADOR2
L2_1S:
    DECFSZ  CONTADOR2, F
    GOTO    L2_1S
    DECFSZ  CONTADOR1, F
    GOTO    L1_1S
    RETURN
    
    
    END