; ** Encabezado **
    LIST P=16F887			
    #include "p16f887.inc"		
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    ;----------------------------VARIABLES------------------------------------------------
CONTADOR1	EQU		 0x20
CONTADOR2	EQU		 0x21
ESTADO		EQU		 0X23
DOBLEV		EQU		 0X24
CUENTA		EQU		0X25

    ORG		0x00
    GOTO		START
    ORG		0X04
    GOTO		INTERRUPCION
    ORG		0x05
    GOTO START
    
    
START:
	BANKSEL			ANSEL
	CLRF			ANSEL
	CLRF			ANSELH
	BANKSEL			TRISA
	MOVLW			b'00000001'		;ENTRADA RBO , SALIDAS RB1 R2 Y RB3
	MOVWF			TRISB
	BANKSEL			PORTA
	BCF			PORTB,1
	BCF			PORTB,2
	BCF			PORTB,3
	
	
	;ESTOY EN EL BANCO DONDE ETA OPTION_REG Y INTCON APROVECHO DE CONFIGURAR AMBOS REGISTROS 
	BANKSEL			OPTION_REG
	BCF			OPTION_REG,0		;CONFIGURO POR FRANCO DESCENDENTE
	
	BSF			INTCON,GIE		;HABILITO INTERRUPCION GLOBAL
	BSF			INTCON,INTE		;HABLITO INTERRUPCION INT POR RBO
	BCF			INTCON,INTF		;LIMPIO EL FLAG DE INTERRUPCION
	
	BANKSEL			PORTA
	CLRF			PORTB
	
	MOVLW			0X26
	MOVWF			FSR
	MOVLW			b'00000010'
	MOVWF			INDF
	INCF			FSR,1
	MOVLW			b'00000100'
	MOVWF			INDF
	INCF			FSR,1
	MOVLW			b'00001000'
	MOVWF			INDF
	MOVLW			0X26
	MOVWF			FSR
	MOVLW			.3
	MOVWF			CUENTA
	loop:
    GOTO loop
    
    
INTERRUPCION:
    ;----------------BORRO EL FLAG DE INT 
	BCF			INTCON,INTF
    ;-----------------------CARGO CONTEXTO
	MOVWF			DOBLEV
	SWAPF			STATUS,W
	MOVWF			ESTADO
	
    ;----------------LOGICA ------------------------
	CALL			DELAY
CAMBIOS:
	    BTFSS			PORTB,0
	    GOTO			DEVUELVOCONTEXTO
	    MOVF			INDF,W
	    MOVWF			PORTB
	    INCF			FSR
	    DECFSZ			CUENTA,1
	    GOTO			DEVUELVOCONTEXTO
	    GOTO			RESET
RESET:
	    MOVLW			0X26
	    MOVWF			FSR
	    MOVLW			.3
	    MOVWF			CUENTA
   ;-------------------------------DEVUELVO CONTEXTO
DEVUELVOCONTEXTO:
	SWAPF			ESTADO,W
	MOVWF			STATUS
	SWAPF			DOBLEV,1
	SWAPF			DOBLEV,W
   
   
   
   RETFIE			    ;HABILITO EL GLOBAL GIE
    
DELAY:
    MOVLW		.50
    MOVWF		CONTADOR1
L1:
    MOVLW		 .50
    MOVWF		 CONTADOR2
L2:	
    DECFSZ		 CONTADOR2, F
    GOTO		  L2
    DECFSZ		 CONTADOR1, F
    GOTO		   L1
    RETURN
	
    
    
    
    END